#! /bin/bash
# chkconfig: 345 85 15
# description: Forever for node.js

DEAMON=/home/admin/zmtextile/project/
LOG=/home/admin/zmtextile/logs/forever.log
PID=/root/.forever/pids/forever.pid
COMMAND="npm start"

export PATH=$PATH:/root/.nvm/v0.10.32/bin/
export NODE_PATH=$NODE_PATH:/root/.nvm/v0.10.32/lib/node_modules/

node=node
forever=forever

case "$1" in
  start)
    $forever start -c $COMMAND -l $LOG --pidFile $PID -a $DEAMON
    ;;
  stop)
    $forever stop --pidFile $PID $DEAMON
    ;;
  stopall)
    $forever stopall --pidFile $PID
    ;;
  restartall)
    $forever restartall --pidFile $PID
    ;;
  reload|restart)
    $forever restart -l $LOG --pidFile $PID -a $DEAMON
    ;;
  list)
    $forever list
    ;;
  *)
    echo  "Usage: /etc.init.d/node{start|stop|restart|reload|stopall|restartall|list}"
    exit 1
    ;;
esac
exit 0